### ISSUE TITLE
too many dialogs if i push quickly

### ISSUE THREAD

**Issue by alejandrofernandezcanton** [likeastore/ngDialog#531] opened 2017-01-25 11:54 UTC
ngDialog --> v0.5.8

AngularJS --> 1.5.8

All browsers

When I push quickly, more than one time, on the button which opens the dialog, this open more than one dialog. I´m using ngDialogProvider.setOpenOnePerName( true ); but the problem is that the dialog is not openned yet because it is loading the template and the controller.

What can i do for opening only one dialog?

Thank you very much!

**Comment by raphaelparent** [comment] 2017-01-26 15:03
You could remove the event (probably a click, or any other event) that triggers the dialog to open. It will let the dialog load what it needs to and open. It will also prevent from triggering the event multiple thus opening more than 1  dialog. 

If this does not help, could you please provide some code example, that could help :)

**Comment by alejandrofernandezcanton** [comment] 2017-01-26 15:24
Finally I put a flag which is changed to false in the first click and i release it in the method opened of the dialog.
    
//this method is called when dialog is opened and it unlocks the variable which locks dialogs
    $scope.releaseDialog = function()
    {
        $rootScope.showDialog = true;
    };
//this method is called in every click. Return true only the first time that is called and it locks the next dialogs
    $scope.checkShowDialog = function()
    {
        if( $rootScope.showDialog == undefined || $rootScope.showDialog )
        {
            $rootScope.showDialog = false;
            return true;
        }
        return false;
    };
//When dialog is opened, it unlocks the variable which locks dialogs
    $rootScope.$on('ngDialog.opened', function (e, $dialog) {
        $scope.releaseDialog();
    });

**Comment by raphaelparent** [comment] 2017-01-26 15:32
Perfect, if the issue is resolved, please close it :)

**Closed** 2017-01-26 15:36 UTC

**Comment by mattiLeBlanc** [comment] 2017-10-09 02:21
Sorry, but issue is not resolved.

We can work around it by adding flags, or my solution:
```
open( config: modalConfig ): ngDialog.IDialogOpenResult {
   const testName = `${ config.name }-dialog`.toLowerCase();
       if ( !!this.ngDialog.getOpenDialogs().filter( item => item === testName ).length ) {
         return;
       }
   return this.ngDialog.open( {
       template: config.template,
       ...
```

however I expect when I set `setOpenOnePerName` to `true` I don't have to do this check myself.
If you are not doing it already, you could add the same test in your `open()` function.
